name: Deploy

on:
  push:
    branches:
      - main

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Ansi2HTML 🐍
        run: pip install ansi2html
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7
      - name: Building website 🚧
        run: julia -e '
          using Pkg;
          Pkg.add(
            url="https://github.com/tlienart/Xranklin.jl",
            rev="main"
          );
          using Xranklin;
          build(
            clear=true,
            prefix="SIIP-Tutorial"
          );'
      - name: No Jekyll
        run: touch ./__site/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ./__site
